# Generated by Django 6.0 on 2026-01-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='edgedevice',
            name='edge_device_is_acti_66b9aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='edgedevice',
            name='edge_device_last_se_de5cf0_idx',
        ),
        migrations.AlterField(
            model_name='edgedevice',
            name='api_key_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterModelTable(
            name='edgedevice',
            table=None,
        ),
        migrations.RemoveField(
            model_name='edgedevice',
            name='allowed_cameras',
        ),
    ]
