# Generated by Django 6.0 on 2026-01-08 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='comments',
            field=models.TextField(blank=True, help_text='Comentarios sobre cambios realizados', null=True),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
