# Generated by Django 6.0.1 on 2026-01-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_company_to_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='camera',
            new_name='camera_company_252ab4_idx',
            old_name='camera_company_idx',
        ),
        migrations.RenameIndex(
            model_name='camera',
            new_name='camera_company_ccc9fb_idx',
            old_name='camera_company_active_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='company_slug_399b14_idx',
            old_name='company_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='company_is_acti_997df1_idx',
            old_name='company_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='report_company_757a5d_idx',
            old_name='report_company_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='report_company_d9b69f_idx',
            old_name='report_company_created_idx',
        ),
        migrations.RenameIndex(
            model_name='usercompanymembership',
            new_name='user_compan_user_id_aaf234_idx',
            old_name='membership_user_company_idx',
        ),
        migrations.RenameIndex(
            model_name='usercompanymembership',
            new_name='user_compan_user_id_549d51_idx',
            old_name='membership_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='usercompanymembership',
            new_name='user_compan_company_63204d_idx',
            old_name='membership_company_active_idx',
        ),
    ]
