# Generated by Django 6.0.1 on 2026-01-23 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_camera_company_idx_camera_company_252ab4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgedevice',
            name='company',
            field=models.ForeignKey(default=1, help_text='Empresa a la que pertenece este dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='edge_devices', to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edgedevice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='edgedevice',
            name='location_name',
            field=models.CharField(blank=True, help_text='Nombre de la ubicación', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='edgedevice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
