# Generated by Django 6.0.5 on 2026-05-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transform_to_golf_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='cashclosure',
            new_name='cash_closur_operati_67d271_idx',
            old_name='cash_closu_operati_f0ef45_idx',
        ),
        migrations.RenameIndex(
            model_name='cashclosure',
            new_name='cash_closur_status_eec556_idx',
            old_name='cash_closu_status_65db1f_idx',
        ),
        migrations.RenameIndex(
            model_name='courseentry',
            new_name='course_entr_created_30d74b_idx',
            old_name='course_entr_created_8849b5_idx',
        ),
        migrations.RenameIndex(
            model_name='courseentry',
            new_name='course_entr_payment_5f846c_idx',
            old_name='course_entr_payment_f6f4ef_idx',
        ),
        migrations.RenameIndex(
            model_name='courseentry',
            new_name='course_entr_created_4fd13f_idx',
            old_name='course_entr_created_4b8057_idx',
        ),
        migrations.RenameIndex(
            model_name='rangeorder',
            new_name='range_order_created_bbd901_idx',
            old_name='range_orde_created_4f65c1_idx',
        ),
        migrations.RenameIndex(
            model_name='rangeorder',
            new_name='range_order_payment_663dee_idx',
            old_name='range_orde_payment_4d0702_idx',
        ),
        migrations.RenameIndex(
            model_name='rangeorder',
            new_name='range_order_created_472150_idx',
            old_name='range_orde_created_4f24cc_idx',
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='course_price_weekday_clp',
            field=models.PositiveIntegerField(default=20000),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='course_price_weekend_clp',
            field=models.PositiveIntegerField(default=25000),
        ),
        migrations.AlterModelTable(
            name='user',
            table='core_user',
        ),
    ]
